/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date2.h"
#include<stdio.h>
#include<stdlib.h>

void
dateprog_1(host, numberof_1_arg)
char *host;
date2  numberof_1_arg;
{
	CLIENT *clnt;
	int  *result_1;
	clnt = clnt_create(host, DATEPROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = numberof_1(&numberof_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("The answer is: %d\n",*result_1);
	clnt_destroy( clnt );
}


main(argc, argv)
int argc;
char *argv[];
{
	char *host;


	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	char day[20];

	date2  temp;
	int day1,day2, month1, month2, year1, year2;
	printf("Enter the day, month and year for date 1\n");
	scanf("%d%d%d",&day1,&month1,&year1);
	printf("Enter the day, month and year for date 2\n");
	scanf("%d%d%d",&day2,&month2,&year2);
	printf("Enter the day to search for\n");
	scanf("%s",day);
	temp.day1 = day1;
	temp.day2 = day2;
	temp.month1 = month1;
	temp.month2 = month2;
	temp.year1 = year1;
	temp.year2 = year2;
	

	if (day[0] == 'M')
	{
		temp.requestedDay = 1;
	}
	else if (day[0] == 'T' && day[1] == 'u')
	{
		temp.requestedDay = 2;
	}
	else if (day[0] == 'W')
	{
		temp.requestedDay = 3;
	}
	else if (day[0] == 'T' && day[1] == 'h')
	{
		temp.requestedDay = 4;
	}
	else if (day[0] == 'F')
	{
		temp.requestedDay = 5;
	}
	else if (day[0] == 'S' && day[1] == 'a')
	{
		temp.requestedDay = 6;
	}
	else if (day[0] == 'S' && day[1] == 'u')
	{
		temp.requestedDay = 0;
	}
	else{
		printf("EROOR: Day not recognized\n");
		exit(1);
	}

	dateprog_1( host,temp );
}
