/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"
#include<stdio.h>
#include<stdlib.h>

void
dateprog_1(host, day, month, year)
char *host;
int day;
int month;
int year;
{
	CLIENT *clnt;
	
	//For first function
	int  *result_1;
	date  numberofleapyears_1_arg;
	numberofleapyears_1_arg.day = day;
	numberofleapyears_1_arg.month = month;
	numberofleapyears_1_arg.year = year;

	//for second function
	int  *result_2;
	date  totaldays_1_arg;
	totaldays_1_arg.day = day;
	totaldays_1_arg.month = month;
	totaldays_1_arg.year = year;

	//For third function
	int  *result_3;
	date  findday_1_arg;
	findday_1_arg.day = day;
	findday_1_arg.month = month;
	findday_1_arg.year = year;

	clnt = clnt_create(host, DATEPROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}


	result_1 = numberofleapyears_1(&numberofleapyears_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}


	result_2 = totaldays_1(&totaldays_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}


	result_3 = findday_1(&findday_1_arg, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main(argc, argv)
int argc;
char *argv[];
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	int day, month, year;

	//Input the date.
	printf("Enter the day, month and the year:");
	scanf("%d%d%d",&day,&month,&year);

	dateprog_1( host, day, month, year );
}
