/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"
#include<stdio.h>
#include<stdlib.h>


void
dateprog1_1(char * host, int day, int month , int year)
{
	CLIENT *clnt;
	int  *result_1;
	date  numberofleapyears_1_arg;
        numberofleapyears_1_arg.day = day;
        numberofleapyears_1_arg.month = month;
        numberofleapyears_1_arg.year = year;

	clnt = clnt_create(host, DATEPROG1, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = numberofleapyears_1(&numberofleapyears_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("%d\n",*result_1);
	clnt_destroy( clnt );
}


void
dateprog2_1(char* host, int day, int month, int year)
{
	CLIENT *clnt;
	int  *result_1;
	date  totaldays_1_arg;
        totaldays_1_arg.day = day;
        totaldays_1_arg.month = month;
        totaldays_1_arg.year = year;	
	clnt = clnt_create(host, DATEPROG2, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = totaldays_1(&totaldays_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("%d\n",*result_1);
	clnt_destroy( clnt );
}


void
dateprog3_1(char *host,int day, int month, int year)
{
	CLIENT *clnt;
	int  *result_1;
	date  findday_1_arg;
        findday_1_arg.day = day;
        findday_1_arg.month = month;
        findday_1_arg.year = year;	
	clnt = clnt_create(host, DATEPROG3, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = findday_1(&findday_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	switch(*result_1)
	{
		case 0: printf("Sunday\n"); break;
		case 1: printf("Monday\n"); break;
		case 2: printf("Tuesday\n"); break;
		case 3: printf("Wednesday\n"); break;
		case 4: printf("Thursday\n"); break;
		case 5: printf("Friday\n"); break;
		case 6: printf("Saturday\n"); break;
		default: printf("Error in getting day\n");
	}
	clnt_destroy( clnt );
}


int main(argc, argv)
int argc;
char *argv[];
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	//Input the date.
        int day, month, year;
	printf("Enter the day, month and the year:");
        scanf("%d%d%d",&day,&month,&year);

	dateprog1_1( host , day, month, year );
	dateprog2_1( host , day, month, year );
	dateprog3_1( host , day, month, year );
}
