/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"

int *
numberofleapyears_1_svc(date *argp, struct svc_req *rqstp)
{

	static int  result;

	int year = argp->year;

	//Check if year in argp is a leap Year
	int flag = 0;
	if ( year%400 == 0)
		flag=1;
  	else if ( year%100 == 0)
    	flag=0;		
    else if ( year%4 == 0 )
    	flag=1;
  	else
    	flag=0;
    

    //Check if feb 28th has passed in case of leap year
    if(flag == 1)
    {
    	int month = argp->month;
    	if (month>=3)
    	{
    		flag=1;
    	}
    	else flag=0;
    }

    //Final Result
	result=(year/400) + (year/4) - (year/100) + flag;

	return(&result);
}

int *
totaldays_1_svc(date *argp, struct svc_req *rqstp)
{

	long long int JDN1 = 1721426; //Julian day number for 01/01/0001
	static int  result;

	int day = argp->day;
	int month = argp->month;
	int year = argp->year;
	
	//Calculating JDN for the input date
	long long int a = (14-month)/12;
	long long int y = year + 4800 - a;
	long long int m = month + 12*a  - 3;

	long long int JDN2 = day + (153*m+2)/5 + 365*y + (y/4) - (y/100) + (y/400) - 32045;

	//Calculating final result
	result = JDN2-JDN1+1;

	return(&result);
}

int *
findday_1_svc(date *argp, struct svc_req *rqstp)
{

	static int  result;
	result = (*totaldays_1_svc(argp, rqstp))%7;

	return(&result);
}
