/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct date {
	int dd;
	int mm;
	int yy;
};
typedef struct date date;
#ifdef __cplusplus
extern "C" bool_t xdr_date(XDR *, date*);
#elif __STDC__
extern  bool_t xdr_date(XDR *, date*);
#else /* Old Style C */
bool_t xdr_date();
#endif /* Old Style C */


#define DATE_PROG ((rpc_uint)0x123456)
#define SIMP_VERSION ((rpc_uint)1)

#ifdef __cplusplus
#define numLeapYears ((rpc_uint)1)
extern "C" int * numleapyears_1(date *, CLIENT *);
extern "C" int * numleapyears_1_svc(date *, struct svc_req *);
#define totalDaysTill ((rpc_uint)2)
extern "C" int * totaldaystill_1(date *, CLIENT *);
extern "C" int * totaldaystill_1_svc(date *, struct svc_req *);
#define day ((rpc_uint)3)
extern "C" int * day_1(date *, CLIENT *);
extern "C" int * day_1_svc(date *, struct svc_req *);

#elif __STDC__
#define numLeapYears ((rpc_uint)1)
extern  int * numleapyears_1(date *, CLIENT *);
extern  int * numleapyears_1_svc(date *, struct svc_req *);
#define totalDaysTill ((rpc_uint)2)
extern  int * totaldaystill_1(date *, CLIENT *);
extern  int * totaldaystill_1_svc(date *, struct svc_req *);
#define day ((rpc_uint)3)
extern  int * day_1(date *, CLIENT *);
extern  int * day_1_svc(date *, struct svc_req *);

#else /* Old Style C */
#define numLeapYears ((rpc_uint)1)
extern  int * numleapyears_1();
extern  int * numleapyears_1_svc();
#define totalDaysTill ((rpc_uint)2)
extern  int * totaldaystill_1();
extern  int * totaldaystill_1_svc();
#define day ((rpc_uint)3)
extern  int * day_1();
extern  int * day_1_svc();
#endif /* Old Style C */

#endif /* !_DATE_H_RPCGEN */
