/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "date.h"

bool_t
xdr_date(xdrs, objp)
	XDR *xdrs;
	date *objp;
{

	if (!xdr_int(xdrs, &objp->dd))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->mm))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->yy))
		return (FALSE);
	return (TRUE);
}
