/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"

int * numberofleapyears_1_svc(date * argp, struct svc_req *rqstp)
{

	static int  result;

	int year = argp->year;

	//Check if year in argp is a leap Year
	int flag = 0;
	if ( year%400 == 0)
		flag=1;
  	else if ( year%100 == 0)
    	flag=0;		
    else if ( year%4 == 0 )
    	flag=1;
  	else
    	flag=0;
    

    //Check if feb 28th has passed in case of leap year
    if(flag == 1)
    {
    	int month = argp->month;
    	if (month>=3)
    	{
    		flag=1;
    	}
    	else flag=0;
    }

    //Final Result
	result=(year/400) + (year/4) - (year/100) + flag;
	
	return(&result);
}
